[2023-04-13T20:40:59.494+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: weather_dag.inject_data_Odesa manual__2023-04-13T20:40:45.638759+00:00 [queued]>
[2023-04-13T20:40:59.523+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: weather_dag.inject_data_Odesa manual__2023-04-13T20:40:45.638759+00:00 [queued]>
[2023-04-13T20:40:59.527+0000] {taskinstance.py:1288} INFO - 
--------------------------------------------------------------------------------
[2023-04-13T20:40:59.532+0000] {taskinstance.py:1289} INFO - Starting attempt 1 of 1
[2023-04-13T20:40:59.534+0000] {taskinstance.py:1290} INFO - 
--------------------------------------------------------------------------------
[2023-04-13T20:40:59.568+0000] {taskinstance.py:1309} INFO - Executing <Task(SqliteOperator): inject_data_Odesa> on 2023-04-13 20:40:45.638759+00:00
[2023-04-13T20:40:59.576+0000] {standard_task_runner.py:55} INFO - Started process 7245 to run task
[2023-04-13T20:40:59.586+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'weather_dag', 'inject_data_Odesa', 'manual__2023-04-13T20:40:45.638759+00:00', '--job-id', '360', '--raw', '--subdir', 'DAGS_FOLDER/weather_dag.py', '--cfg-path', '/tmp/tmpf7a4lyh4']
[2023-04-13T20:40:59.589+0000] {standard_task_runner.py:83} INFO - Job 360: Subtask inject_data_Odesa
[2023-04-13T20:40:59.706+0000] {task_command.py:389} INFO - Running <TaskInstance: weather_dag.inject_data_Odesa manual__2023-04-13T20:40:45.638759+00:00 [running]> on host ffea11fb791c
[2023-04-13T20:40:59.882+0000] {taskinstance.py:1518} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=weather_dag
AIRFLOW_CTX_TASK_ID=inject_data_Odesa
AIRFLOW_CTX_EXECUTION_DATE=2023-04-13T20:40:45.638759+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-04-13T20:40:45.638759+00:00
[2023-04-13T20:40:59.884+0000] {sql.py:254} INFO - Executing: 
                INSERT INTO measures_ext (city, timestamp, temp, humidity, cloudiness, wind_speed) VALUES
                    ("Odesa",
                    1681418282,
                    282.75,
                    80,
                    "scattered clouds",
                    3.46);
            
[2023-04-13T20:40:59.897+0000] {base.py:73} INFO - Using connection ID 'measure_db' for task execution.
[2023-04-13T20:41:00.195+0000] {base.py:73} INFO - Using connection ID 'measure_db' for task execution.
[2023-04-13T20:41:00.203+0000] {sql.py:375} INFO - Running statement: 
                INSERT INTO measures_ext (city, timestamp, temp, humidity, cloudiness, wind_speed) VALUES
                    ("Odesa",
                    1681418282,
                    282.75,
                    80,
                    "scattered clouds",
                    3.46);
            , parameters: None
[2023-04-13T20:41:00.231+0000] {sql.py:384} INFO - Rows affected: 1
[2023-04-13T20:41:00.272+0000] {taskinstance.py:1332} INFO - Marking task as SUCCESS. dag_id=weather_dag, task_id=inject_data_Odesa, execution_date=20230413T204045, start_date=20230413T204059, end_date=20230413T204100
[2023-04-13T20:41:00.323+0000] {local_task_job.py:212} INFO - Task exited with return code 0
[2023-04-13T20:41:00.360+0000] {taskinstance.py:2596} INFO - 0 downstream tasks scheduled from follow-on schedule check
