[2023-04-13T20:19:14.201+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: weather_dag.inject_data_Kyiv manual__2023-04-13T20:19:01.842128+00:00 [queued]>
[2023-04-13T20:19:14.264+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: weather_dag.inject_data_Kyiv manual__2023-04-13T20:19:01.842128+00:00 [queued]>
[2023-04-13T20:19:14.268+0000] {taskinstance.py:1288} INFO - 
--------------------------------------------------------------------------------
[2023-04-13T20:19:14.270+0000] {taskinstance.py:1289} INFO - Starting attempt 1 of 1
[2023-04-13T20:19:14.275+0000] {taskinstance.py:1290} INFO - 
--------------------------------------------------------------------------------
[2023-04-13T20:19:14.310+0000] {taskinstance.py:1309} INFO - Executing <Task(SqliteOperator): inject_data_Kyiv> on 2023-04-13 20:19:01.842128+00:00
[2023-04-13T20:19:14.320+0000] {standard_task_runner.py:55} INFO - Started process 6678 to run task
[2023-04-13T20:19:14.335+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'weather_dag', 'inject_data_Kyiv', 'manual__2023-04-13T20:19:01.842128+00:00', '--job-id', '279', '--raw', '--subdir', 'DAGS_FOLDER/weather_dag.py', '--cfg-path', '/tmp/tmpwa8l7zok']
[2023-04-13T20:19:14.338+0000] {standard_task_runner.py:83} INFO - Job 279: Subtask inject_data_Kyiv
[2023-04-13T20:19:14.745+0000] {task_command.py:389} INFO - Running <TaskInstance: weather_dag.inject_data_Kyiv manual__2023-04-13T20:19:01.842128+00:00 [running]> on host ffea11fb791c
[2023-04-13T20:19:15.121+0000] {taskinstance.py:1518} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=weather_dag
AIRFLOW_CTX_TASK_ID=inject_data_Kyiv
AIRFLOW_CTX_EXECUTION_DATE=2023-04-13T20:19:01.842128+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-04-13T20:19:01.842128+00:00
[2023-04-13T20:19:15.124+0000] {sql.py:254} INFO - Executing: 
                INSERT INTO measures_ext (timestamp, temp, humidity, cloudiness, wind_speed) VALUES
                    (1681416405,
                    283.52,
                    82,
                    "overcast clouds",
                    0.45);
            
[2023-04-13T20:19:15.159+0000] {base.py:73} INFO - Using connection ID 'measure_db' for task execution.
[2023-04-13T20:19:15.926+0000] {base.py:73} INFO - Using connection ID 'measure_db' for task execution.
[2023-04-13T20:19:15.933+0000] {sql.py:375} INFO - Running statement: 
                INSERT INTO measures_ext (timestamp, temp, humidity, cloudiness, wind_speed) VALUES
                    (1681416405,
                    283.52,
                    82,
                    "overcast clouds",
                    0.45);
            , parameters: None
[2023-04-13T20:19:15.961+0000] {sql.py:384} INFO - Rows affected: 1
[2023-04-13T20:19:16.013+0000] {taskinstance.py:1332} INFO - Marking task as SUCCESS. dag_id=weather_dag, task_id=inject_data_Kyiv, execution_date=20230413T201901, start_date=20230413T201914, end_date=20230413T201916
[2023-04-13T20:19:16.128+0000] {local_task_job.py:212} INFO - Task exited with return code 0
[2023-04-13T20:19:16.204+0000] {taskinstance.py:2596} INFO - 0 downstream tasks scheduled from follow-on schedule check
